<a href="https://colab.research.google.com/github/N2000-hack/Machine-Learning-LAB/blob/main/EXP_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [33]:
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [34]:
cancer_data=np.genfromtxt(
    fname='/content/drive/MyDrive/ML LAB DATASETS/breast-cancer-wisconsin (2).data',delimiter=',',dtype=float)

In [35]:
print("Dataset Length:: ", len(cancer_data))

Dataset Length::  699


In [36]:
print("Dataset:: ", str(cancer_data))

Dataset::  [[1.000025e+06 5.000000e+00 1.000000e+00 ... 1.000000e+00 1.000000e+00
  2.000000e+00]
 [1.002945e+06 5.000000e+00 4.000000e+00 ... 2.000000e+00 1.000000e+00
  2.000000e+00]
 [1.015425e+06 3.000000e+00 1.000000e+00 ... 1.000000e+00 1.000000e+00
  2.000000e+00]
 ...
 [8.888200e+05 5.000000e+00 1.000000e+01 ... 1.000000e+01 2.000000e+00
  4.000000e+00]
 [8.974710e+05 4.000000e+00 8.000000e+00 ... 6.000000e+00 1.000000e+00
  4.000000e+00]
 [8.974710e+05 4.000000e+00 8.000000e+00 ... 4.000000e+00 1.000000e+00
  4.000000e+00]]


In [37]:
print("Dataset Shape:: ",(cancer_data.shape))

Dataset Shape::  (699, 11)


In [38]:
print(cancer_data)

[[1.000025e+06 5.000000e+00 1.000000e+00 ... 1.000000e+00 1.000000e+00
  2.000000e+00]
 [1.002945e+06 5.000000e+00 4.000000e+00 ... 2.000000e+00 1.000000e+00
  2.000000e+00]
 [1.015425e+06 3.000000e+00 1.000000e+00 ... 1.000000e+00 1.000000e+00
  2.000000e+00]
 ...
 [8.888200e+05 5.000000e+00 1.000000e+01 ... 1.000000e+01 2.000000e+00
  4.000000e+00]
 [8.974710e+05 4.000000e+00 8.000000e+00 ... 6.000000e+00 1.000000e+00
  4.000000e+00]
 [8.974710e+05 4.000000e+00 8.000000e+00 ... 4.000000e+00 1.000000e+00
  4.000000e+00]]


In [39]:
cancer_data=np.delete(arr=cancer_data,obj=0,axis=1)

In [40]:
X=cancer_data[:,range(0,9)]
X

array([[ 5.,  1.,  1., ...,  3.,  1.,  1.],
       [ 5.,  4.,  4., ...,  3.,  2.,  1.],
       [ 3.,  1.,  1., ...,  3.,  1.,  1.],
       ...,
       [ 5., 10., 10., ...,  8., 10.,  2.],
       [ 4.,  8.,  6., ..., 10.,  6.,  1.],
       [ 4.,  8.,  8., ..., 10.,  4.,  1.]])

In [41]:
Y=cancer_data[:,9]
Y

array([2., 2., 2., 2., 2., 4., 2., 2., 2., 2., 2., 2., 4., 2., 4., 4., 2.,
       2., 4., 2., 4., 4., 2., 4., 2., 4., 2., 2., 2., 2., 2., 2., 4., 2.,
       2., 2., 4., 2., 4., 4., 2., 4., 4., 4., 4., 2., 4., 2., 2., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 2., 4., 4., 2., 4., 2., 4.,
       4., 2., 2., 4., 2., 4., 4., 2., 2., 2., 2., 2., 2., 2., 2., 2., 4.,
       4., 4., 4., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 4., 4., 4., 4.,
       2., 4., 4., 4., 4., 4., 2., 4., 2., 4., 4., 4., 2., 2., 2., 4., 2.,
       2., 2., 2., 4., 4., 4., 2., 4., 2., 4., 2., 2., 2., 4., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 4., 2., 2., 2., 4., 2., 2., 4., 2., 4., 4.,
       2., 2., 4., 2., 2., 2., 4., 4., 2., 2., 2., 2., 2., 4., 4., 2., 2.,
       2., 2., 2., 4., 4., 4., 2., 4., 2., 4., 2., 2., 2., 4., 4., 2., 4.,
       4., 4., 2., 4., 4., 2., 2., 2., 2., 2., 2., 2., 2., 4., 4., 2., 2.,
       2., 4., 4., 2., 2., 2., 4., 4., 2., 4., 4., 4., 2., 2., 4., 2., 2.,
       4., 4., 4., 4., 2.

In [44]:
imp=SimpleImputer(missing_values=np.nan,strategy='median')
X=imp.fit_transform(X)

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=100)
y_train = y_train.ravel()
y_test = y_test.ravel()

In [46]:
X_train

array([[ 1.,  1.,  1., ...,  2.,  1.,  1.],
       [ 9., 10., 10., ..., 10., 10.,  1.],
       [ 1.,  1.,  1., ...,  3.,  1.,  1.],
       ...,
       [ 5.,  1.,  1., ...,  1.,  1.,  1.],
       [ 2.,  1.,  1., ...,  2.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.]])

In [47]:
X_test

array([[2., 1., 1., ..., 1., 1., 1.],
       [4., 4., 4., ..., 7., 3., 1.],
       [8., 9., 9., ..., 7., 7., 1.],
       ...,
       [5., 1., 1., ..., 2., 1., 1.],
       [5., 1., 2., ..., 3., 1., 1.],
       [3., 1., 1., ..., 3., 1., 1.]])

In [48]:
y_train

array([2., 4., 2., 2., 4., 2., 2., 2., 2., 2., 2., 2., 2., 2., 4., 2., 2.,
       2., 4., 2., 2., 4., 2., 4., 2., 2., 2., 4., 4., 2., 2., 4., 2., 4.,
       4., 4., 4., 4., 2., 2., 2., 4., 2., 2., 4., 2., 2., 2., 2., 2., 4.,
       2., 2., 2., 2., 2., 2., 2., 2., 4., 2., 2., 4., 2., 4., 2., 2., 2.,
       2., 2., 2., 2., 4., 4., 2., 2., 4., 4., 2., 4., 4., 2., 4., 2., 2.,
       2., 4., 2., 2., 4., 2., 4., 2., 2., 2., 2., 2., 2., 2., 4., 4., 4.,
       2., 2., 2., 2., 2., 2., 2., 4., 2., 2., 4., 4., 4., 4., 2., 4., 2.,
       4., 2., 2., 2., 4., 4., 2., 2., 2., 4., 4., 2., 2., 4., 2., 2., 2.,
       4., 4., 4., 4., 2., 2., 2., 2., 2., 2., 2., 2., 4., 4., 4., 2., 4.,
       2., 2., 2., 2., 2., 2., 4., 2., 4., 2., 2., 2., 2., 4., 4., 2., 4.,
       2., 4., 2., 2., 2., 2., 4., 2., 4., 2., 2., 2., 2., 4., 2., 4., 2.,
       4., 4., 2., 2., 2., 2., 4., 4., 2., 2., 2., 2., 2., 2., 2., 2., 4.,
       2., 2., 2., 2., 2., 2., 4., 4., 4., 2., 2., 4., 2., 2., 4., 2., 2.,
       4., 4., 2., 4., 2.

In [49]:
y_test

array([2., 2., 4., 4., 2., 2., 2., 2., 4., 2., 4., 2., 2., 2., 4., 2., 2.,
       2., 2., 4., 4., 2., 2., 2., 4., 2., 4., 4., 2., 4., 2., 4., 2., 4.,
       4., 4., 4., 2., 4., 2., 2., 4., 2., 4., 2., 2., 2., 2., 2., 2., 4.,
       2., 2., 4., 4., 2., 2., 2., 2., 2., 2., 2., 4., 2., 4., 2., 4., 2.,
       2., 4., 2., 4., 2., 4., 4., 2., 4., 2., 4., 4., 2., 2., 2., 2., 4.,
       4., 2., 2., 2., 4., 2., 4., 2., 2., 2., 4., 2., 2., 2., 2., 4., 4.,
       4., 4., 4., 4., 2., 2., 4., 4., 2., 2., 2., 2., 2., 2., 4., 4., 4.,
       4., 2., 4., 2., 2., 2., 2., 2., 4., 2., 2., 2., 4., 2., 4., 4., 4.,
       4., 2., 4., 2., 4., 2., 2., 2., 2., 4., 4., 4., 4., 2., 2., 2., 4.,
       4., 2., 2., 2., 4., 2., 2., 4., 4., 2., 2., 2., 2., 2., 2., 4., 4.,
       2., 2., 2., 2., 4., 2., 4., 2., 2., 2., 4., 2., 2., 2., 2., 2., 2.,
       4., 2., 2., 2., 4., 4., 2., 2., 2., 4., 2., 2., 2., 2., 4., 2., 4.,
       4., 4., 4., 2., 2., 2.])

In [50]:
for K in range(25):
  K_value=K+1
  neigh=KNeighborsClassifier(n_neighbors=K_value,weights='uniform',algorithm='auto')
  neigh.fit(X_train, y_train)
  y_pred=neigh.predict(X_test)
  print(" Accuracy is ",accuracy_score(y_test,y_pred)*100,"% for K-Value: ",K_value)

 Accuracy is  95.23809523809523 % for K-Value:  1
 Accuracy is  93.33333333333333 % for K-Value:  2
 Accuracy is  95.71428571428572 % for K-Value:  3
 Accuracy is  95.23809523809523 % for K-Value:  4
 Accuracy is  95.71428571428572 % for K-Value:  5
 Accuracy is  94.76190476190476 % for K-Value:  6
 Accuracy is  94.76190476190476 % for K-Value:  7
 Accuracy is  94.28571428571428 % for K-Value:  8
 Accuracy is  94.76190476190476 % for K-Value:  9
 Accuracy is  94.28571428571428 % for K-Value:  10
 Accuracy is  94.28571428571428 % for K-Value:  11
 Accuracy is  94.76190476190476 % for K-Value:  12
 Accuracy is  94.76190476190476 % for K-Value:  13
 Accuracy is  93.80952380952381 % for K-Value:  14
 Accuracy is  93.80952380952381 % for K-Value:  15
 Accuracy is  93.80952380952381 % for K-Value:  16
 Accuracy is  93.80952380952381 % for K-Value:  17
 Accuracy is  93.80952380952381 % for K-Value:  18
 Accuracy is  93.80952380952381 % for K-Value:  19
 Accuracy is  93.80952380952381 % for K-